export const ADD_PIECE = 'ADD_PIECE';
export const BACKDROP_CLICKED = 'BACKDROP_CLICKED';
export const HANDLE_CONFIGURE = 'HANDLE_CONFIGURE';
export const MERGE_MODAL_AND_FORM = 'MERGE_MODAL_AND_FORM';